---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Five little girls, of Five, Four, Three, Two, One:  
Rolling on the hearthrug, full of tricks and fun.   
  
Five rosy girls, in years from Ten to Six:  
Sitting down to lessons - no more time for tricks.   
  
Five growing girls, from Fifteen to Eleven:  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Because I have come to the fence at night,   
the horses arrive also from their ancient stable.   
They let me stroke their long faces, and I note   
in the light of the now-merging moon  
  
how they, a Morgan and a Quarter, have been   
by shake-guttered raindrops   
spotted around their rumps and thus made   
Appaloosas, the ancestral horses of this place.  
  
Maybe because it is night, they are nervous,   
or maybe because they too sense   
what they have become, they seem   
to be waiting for me to say something  
  
to whatever ancient spirits might still abide here,   
that they might awaken from this strange dream,   
in which there are fences and stables and a man   
who doesn’t know a single word they understand.  